Repository Geoportail-Luxembourg/geoportailv3, pull requests merged in 2018-07, with the labels that each got.

#2080 Add parcel information in response
  geoportailv3/geocode.py
  geoportailv3/views/geocode.py
Labels: in progress

#2081 remove slider when no layer
  geoportailv3/static/js/slider/slider.js
Labels: in progress

#2082 Use z-index in print
  geoportailv3/static/js/print/printdirective.js
  geoportailv3/static/js/print/printservice.js
Labels: in progress

#2083 Regularly store tiles and estimate tiles download size
  geoportailv3/static/js/appmodule.js
  geoportailv3/static/js/mymapsserviceoffline.js
  geoportailv3/static/js/offline/Configuration.js
  geoportailv3/static/js/offlineDownloader.js
  geoportailv3/static/js/offlineNgeoComponent.html
  geoportailv3/static/js/offlineRestorer.js
  package.json
Labels: in progress

#2079 Offline state integration
  geoportailv3/static/js/draw/featurepopupdirective.js
  geoportailv3/static/js/infobar/infobar.html
  geoportailv3/static/js/maincontroller.js
  geoportailv3/static/js/mymapsservice.js
  geoportailv3/static/js/offlineNgeoComponent.html
  geoportailv3/static/js/offlineRestorer.js
  geoportailv3/static/less/offline.less
  geoportailv3/templates/index.html
  package.json
Labels: in progress, offline

#2084 Remove features with invalid geometry from the kml
  geoportailv3/static/js/mymaps/mymapsdirective.js
Labels: in progress

#2085 Fix appcache
  geoportailv3/static/js/appmodule.js
  geoportailv3/templates/geoportailv3.appcache
Labels: in progress

#2086 Hide the KML/GPX download feature when offline
  geoportailv3/static/less/offline.less
Labels: in progress, offline

#2087 Fix activation right after download
  package.json
Labels: in progress, offline

#2089 Offline fixes
  package.json
Labels: in progress

#2090 Fix master
  geoportailv3/static/js/print/printservice.js
  package.json
Labels: in progress

#2091 Merge master into offline branch
  geoportailv3/__init__.py
  geoportailv3/geocode.py
  geoportailv3/mymaps.py
  geoportailv3/routing.py
  geoportailv3/static/js/draw/drawdirective.js
  geoportailv3/static/js/draw/drawnfeaturesservice.js
  geoportailv3/static/js/maincontroller.js
  geoportailv3/static/js/mymaps/mymaps.html
  geoportailv3/static/js/mymaps/mymapsdirective.js
  geoportailv3/static/js/mymapsservice.js
  geoportailv3/static/js/mymapsserviceoffline.js
  geoportailv3/static/js/offline/Configuration.js
  geoportailv3/static/js/offlineDownloader.js
  geoportailv3/static/js/offlineRestorer.js
  geoportailv3/static/js/print/printdirective.js
  geoportailv3/static/js/print/printservice.js
  geoportailv3/static/js/slider/slider.js
  geoportailv3/static/less/layout.less
  geoportailv3/views/appcache.py
  geoportailv3/views/geocode.py
  geoportailv3/views/getfeatureinfo.py
  geoportailv3/views/mymaps.py
  geoportailv3/views/pag.py
  geoportailv3/views/wms.py
Labels: in progress

#2093 Improve offline actions
  geoportailv3/static/js/offlineNgeoComponent.html
  geoportailv3/templates/index.html
  package.json
Labels: offline

#2097 Better calculation of size to download
  geoportailv3/static/js/offline/Configuration.js
  geoportailv3/static/js/offlineNgeoComponent.html
  package.json
Labels: in progress, offline

#2101 Fix themes caching
  geoportailv3/templates/geoportailv3.appcache
Labels: offline

#2106 Offline fix
  geoportailv3/static/js/offlineRestorer.js
  geoportailv3/static/less/offline.less
  package.json
Labels: offline
